workflows:
  ios-testing:
    name: iOS Build and Test
    environment:
      xcode: 11.0  # Specify the Xcode version
      cocoapods: default
      vars:
        CORDOVA_PLATFORM: "ios"  # Set Cordova platform to iOS
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install -g cordova
          npm install
      - name: Add iOS platform to Cordova
        script: |
          cordova platform add ios
      - name: Build the iOS app for testing
        script: |
          cordova build ios
      - name: Run unit tests (if applicable)
        script: |
          if [ -d "tests" ]; then
            npm run test
          else
            echo "No tests found, skipping..."
          fi
  
    publishing:
      email:
        recipients:
          - dikagoray@gmail.com  # Add your email to receive notifications
