workflows:
  ios-testing:
    name: iOS Build and Test
    environment:
      xcode: 15.1
      cocoapods: default
      vars:
        CORDOVA_PLATFORM: "ios"
    scripts:
      - name: Navigate to the Cordova project directory
        script: |
          cd cordova  # Adjust this path to your Cordova project
      - name: Install dependencies
        script: |
          npm install -g cordova
          npm install
      - name: Add iOS platform
        script: |
          cordova platform add ios
      - name: Build for iOS
        script: |
          cordova build ios
    artifacts:
      - path: cordova/platforms/ios/build/emulator/
        type: folder
