workflows:
  ios-testing:
    name: iOS Build and Test
    environment:
      xcode: 15.1
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install -g cordova
          npm install
      - name: Add iOS platform
        script: |
          cordova platform add ios
      - name: Build for iOS
        script: |
          cordova build ios
        artifacts:
      - path: platforms/ios/build/emulator/*.app
        type: folder

   
