workflows:
  ios-testing:
    name: iOS Build and Test
    environment:
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install -g cordova
          npm install
      - name: Add iOS platform
        script: |
          cordova platform add ios
      - name: Build for iOS
        script: |
          cordova build ios
      - name: Debug build directory
        script: |
          echo "iOS Build directory contents:"
          ls -R platforms/ios/build
    artifacts:
      - platforms/ios/build/*.ipa
type: file
