workflows:
  cordova-ios-android:
    name: Cordova iOS
    environment:
      node: 16.13.0  # Specify the Node.js version
      vars:
        # Define any environment variables, like API keys
        CORDOVA_PLATFORM: "ios"  # Change to "android" for Android builds
    scripts:
      - name: Add Cordova platforms
        script: |
          cordova platform add $CORDOVA_PLATFORM
      - name: Build for iOS
        script: |
          if [ "$CORDOVA_PLATFORM" == "ios" ]; then
            cordova build ios --release
          fi
    artifacts:
      - build/*  # Adjust the path for iOS and Android output files
    publishing:
      email:
        recipients:
          - dikagoray@gmail.com  # Add your email to receive build notifications
